[package]
name = "day7"
version = "0.1.0"
authors = ["Frank Wang <frank@circleci.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode_computer = { path = "../intcode_computer" }
itertools = "0.8.2"